package com.aeliavision.androiddeck.core.baseline

/**
 *
 * A Baseline Profile pre-compiles the most critical hot paths of the app's bytecode
 * into native code at install time (via ART's Cloud Profile or APK-embedded profile),
 * giving up to 30 % faster startup and smoother first-frame rendering.
 *
 * HOW TO GENERATE THE ACTUAL PROFILE
 * ------------------------------------
 * 1. Add a :baseline-profile Gradle module (see baselineProfileModule below).
 * 2. Connect a physical device / emulator running Android 9+ (API 28+).
 * 3. Run:  ./gradlew :app:generateBaselineProfile
 * 4. The generated `baseline-prof.txt` is written to
 *    app/src/main/baseline-prof.txt and embedded in the release APK/AAB.
 *
 * The profileinstaller dependency (already in app/build.gradle.kts) ensures the
 * profile is installed on Android 7–8 devices that don't support Cloud Profiles.
 *
 * BASELINE PROFILE RULES FILE
 * ----------------------------
 * Place critical class/method patterns in:
 *   app/src/main/baseline-prof.txt
 *
 * Example rules (generated automatically by the Macrobenchmark library):
 *   HSPLcom.aeliavision.androiddeck/MainActivity;->onCreate(Landroid/os/Bundle;)V
 *   Lcom.aeliavision.androiddeck/feature/contacts/ui/list/ContactListScreen;
 *   Lcom.aeliavision.androiddeck/core/ui/theme/Theme;
 */
object BaselineProfileProvider {
    // This object is intentionally empty.
    // The actual profile is generated by the :baseline-profile macrobenchmark module
    // and stored as a text file at app/src/main/baseline-prof.txt.
    // See the doc comment above for generation instructions.
}
